version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx/certs:/etc/letsencrypt:ro
      - ./data/nginx/www:/var/www/html
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot-renewal
    volumes:
      - ./data/nginx/certs:/etc/letsencrypt
      - ./data/nginx/www:/var/www/html
    entrypoint: /bin/sh -c
    command: "trap exit TERM; while :; do certbot renew --webroot -w /var/www/html --quiet; sleep 12h & wait $${!}; done"
    restart: always
