services:
  app:
    read_only: true
    tmpfs:
      - /tmp
      # Laravel View Cache
      - /var/www/storage/framework/views:uid=82,gid=82,mode=1777
      # Laravel Cache (config, route)
      - /var/www/storage/framework/cache:uid=82,gid=82,mode=1777
      # Bootstrap Cache (config.php, routes.php...)
      - /var/www/bootstrap/cache:uid=82,gid=82,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop: [ ALL ]
    cap_add: [ CHOWN, SETUID, SETGID ]
    image: pasubi/crypto-tracker-app:${IMAGE_TAG}
    container_name: crypto-tracker-app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "9000:9000"

  worker:
    image: pasubi/crypto-tracker-app:${IMAGE_TAG}
    container_name: crypto-tracker-worker
    entrypoint: []
    command: >
      sh -c "php artisan queue:work redis
             --sleep=3
             --tries=3
             --timeout=90"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:15
    container_name: crypto-tracker-postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7-alpine
    container_name: crypto-tracker-redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6379:6379"

  nginx:
    image: pasubi/crypto-tracker-nginx:${IMAGE_TAG}
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /run
    security_opt:
      - no-new-privileges:true
    cap_drop: [ ALL ]
    cap_add: [ CHOWN, SETUID, SETGID ]
    container_name: crypto-tracker-nginx
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  pgdata:
