services:
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
        image: crypto-tracker-app:dev
        container_name: crypto-tracker-app
        working_dir: /var/www
        volumes:
            - ./crypto-tracker:/var/www:cached
            - ./certs:/etc/nginx/certs:ro
        env_file:
            - .env
        environment:
            APP_ENV: local
            XDEBUG_MODE: debug,develop
            XDEBUG_CONFIG: client_host=host.docker.internal
        depends_on:
            - db
            - redis
        ports:
            - "9000:9000"
            - "9003:9003"

    nginx:
        image: nginx:alpine
        container_name: crypto-tracker-nginx
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certs:/etc/nginx/certs:ro
            - ./crypto-tracker:/var/www:ro
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: crypto-tracker-postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: crypto-tracker-redis
        ports:
            - "6379:6379"

    worker:
        build:
            context: .
            dockerfile: dev.Dockerfile
        image: crypto-tracker-worker:dev
        container_name: crypto-tracker-worker
        working_dir: /var/www
        command: >
            sh -c "php artisan queue:work redis
                   --sleep=3
                   --tries=3
                   --timeout=90"
        volumes:
            - ./crypto-tracker:/var/www:cached
            - ./.env:/var/www/.env
        env_file:
            - .env
        depends_on:
            - redis
            - db

    tunnel:
      image: ngrok/ngrok:latest
      container_name: crypto-tracker-tunnel
      ports:
        - "4041:4040"
      command:
        - "http"
        - "nginx:80"
      environment:
        - NGROK_AUTHTOKEN=39tPqpRtt9XDCwnxIHUD1GvyDd4_678dRcxrtLyR6KmkmKgsC
      depends_on:
        - nginx

volumes:
    pgdata:
